# Generated by Django 4.2.4 on 2023-09-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
