# Generated by Django 4.2.4 on 2023-09-07 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_rename_f_name_info_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
