# Generated by Django 4.2.4 on 2023-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_info_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('create', 'Create'), ('published', 'Published')], default='draft'),
        ),
    ]
